# Generated by Django 4.0 on 2023-07-15 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_notes.course')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='all_videos',
            field=models.ManyToManyField(blank=True, null=True, related_name='playlists', to='courses_notes.videos'),
        ),
    ]
