# Generated by Django 4.0 on 2023-07-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_notes', '0002_videos_playlist_all_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='videos',
            field=models.ManyToManyField(related_name='dashboards', to='courses_notes.Videos'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='all_videos',
            field=models.ManyToManyField(blank=True, null=True, related_name='playlists', to='courses_notes.Videos'),
        ),
    ]
