# Generated by Django 4.0 on 2023-07-15 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
        ('courses_notes', '0004_alter_playlist_all_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userAuth.myuser', to_field='email'),
        ),
    ]
