# Generated by Django 4.1.10 on 2023-07-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses_notes", "0005_alter_dashboard_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="videos",
            name="codes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videos",
            name="video_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
