# Generated by Django 4.1.10 on 2023-07-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses_notes", "0007_videos_videonumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AllNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("notes_link", models.CharField(blank=True, max_length=255, null=True)),
                ("notesNumber", models.IntegerField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses_notes.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dashboard",
            name="all_notes",
            field=models.ManyToManyField(
                related_name="dashboards", to="courses_notes.allnotes"
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="all_notes",
            field=models.ManyToManyField(
                blank=True, related_name="notes", to="courses_notes.allnotes"
            ),
        ),
    ]
