# Generated by Django 4.1.10 on 2023-07-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses_notes",
            "0013_monthlyuserprogress_year_weeklyprogress_month_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="videos",
            name="videoDuration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
