# Generated by Django 4.1.10 on 2023-07-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses_notes", "0015_remove_videos_videoduration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos",
            name="videoDurationInHours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
