# Generated by Django 4.2.2 on 2023-07-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_notes', '0018_course_image_link_note_image_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='all_notes',
            field=models.ManyToManyField(blank=True, related_name='dashboards', to='courses_notes.allnotes'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='dashboards', to='courses_notes.course'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='dashboards', to='courses_notes.note'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='dashboards', to='courses_notes.playlist'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='dashboards', to='courses_notes.videos'),
        ),
    ]
