# Generated by Django 3.2.8 on 2023-09-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_myuser_dyn_myuser_gstin_myuser_business_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='DYN',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='GSTIN',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='business_website',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='industry_category',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
    ]
