# Generated by Django 4.0 on 2023-07-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_userprofile_about_userprofile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='img',
            field=models.ImageField(blank=True, upload_to='post_img'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_img'),
        ),
    ]
