# Generated by Django 4.1.10 on 2023-07-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses_notes", "0006_videos_codes_videos_video_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="videos",
            name="videoNumber",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
