# Generated by Django 4.1.10 on 2023-07-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses_notes",
            "0008_alter_note_content_allnotes_dashboard_all_notes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
