# Generated by Django 4.1.10 on 2023-07-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses_notes", "0012_monthlyuserprogress_weeklyprogress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyuserprogress",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name="weeklyprogress",
            name="month_number",
            field=models.IntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="weeklyprogress",
            name="week_number",
            field=models.IntegerField(
                choices=[
                    (1, "Week 1"),
                    (2, "Week 2"),
                    (3, "Week 3"),
                    (4, "Week 4"),
                    (5, "Week 5"),
                ],
                default=1,
            ),
        ),
    ]
