# Generated by Django 4.1.10 on 2023-07-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses_notes", "0014_videos_videoduration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videos",
            name="videoDuration",
        ),
        migrations.AddField(
            model_name="videos",
            name="videoDurationInHours",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
