# Generated by Django 4.1.10 on 2023-07-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses_notes", "0017_alter_videos_videodurationinhours"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="image_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="image_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
