# Generated by Django 4.2.1 on 2023-09-09 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userAccount", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="name",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(blank=True, upload_to="profile_img"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
        ),
        migrations.CreateModel(
            name="UserPosts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "business_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "state_province",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("job_title", models.CharField(blank=True, max_length=255, null=True)),
                ("job_description", models.TextField(blank=True, null=True)),
                ("job_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "job_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("required_skills", models.TextField(blank=True, null=True)),
                (
                    "experience_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "education_requirements",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "job_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("how_to_apply", models.TextField(blank=True, null=True)),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("application_instructions", models.TextField(blank=True, null=True)),
                ("job_poster_linkedin", models.URLField(blank=True, null=True)),
                (
                    "terms_and_conditions_accepted",
                    models.BooleanField(blank=True, null=True),
                ),
                ("privacy_policy_accepted", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="email",
                    ),
                ),
            ],
        ),
    ]
